### ISSUE TITLE
line # 93 is bugged

### ISSUE THREAD

**Issue by IktaSorlok** [radx5Blue/ImmersiveSolarArrays#14]
Line number #93 is bugged according to project zomboid debug, that came up after I fixed line #53 by adding the missing s to the inverter spawn place
as for how to fix line #93 I have no clue as I can't even really tell whats wrong with it, but it is complaining about it
oh, the file I'm talking about is the Item distribution file, ISADistList.lua

**Comment by ttr** [comment]
it's duplicate of:https://github.com/radx5Blue/ImmersiveSolarArrays/issues/8
all of those lines missing letter s

**Comment by radx5Blue** [comment]
Is this still bugged on the repo, fix it if it is.

**Comment by ttr** [comment]
no, in repo is fine - https://github.com/radx5Blue/ImmersiveSolarArrays/pull/11/ fixed it.

**Comment by radx5Blue** [comment]
fixed
