### ISSUE TITLE
Stove use electricity when powered off.

### ISSUE THREAD

**Issue by ttr** [radx5Blue/ImmersiveSolarArrays#15]
**Describe the bug**
Stove use electricity when powered off.

SolarMovables.lua, line 209 - checking for isPowered() will be always true as stove is on powered grid.

changing it to ```if instanceof(myObject, "IsoStove") and myObject:Activated() then``` should work correctly
also, power usage you could do by ratio of getMaxTemperature() and IIRC 300f

**Comment by radx5Blue** [comment]
I will add this in soon, thanks

**Comment by Jesseman1** [comment]
where is this file found?

**Comment by ttr** [comment]
@Jesseman1 media/lua/client/Moveables/SolarMoveables.lua

**Comment by Jesseman1** [comment]
I don't have any experience with editing PZ mods so I'm kinda lost. I checked the main PZ game in the directory you specified but this file isn't there. I thought this might be similar to 7dtd mods where you can edit them on your local system but maybe I'm wrong and just need to wait for the mod to be updated.

**Comment by ttr** [comment]
@Jesseman1 if it's steam, than it's in workshop directory - on same drive as you have PZ installed, in workshop\content\108600\2623458493\mods\ImmersiveSolarArrays\media\lua\client

**Comment by Jesseman1** [comment]
OHHHH! I finally found it! I kept thinking it was in ProjectZomboid > Workshop
I never thought to look in SteamLibrary > Workshop

**Comment by radx5Blue** [comment]
Fixed, uploading soon
