### ISSUE TITLE
[feature request] Wind turbines

### ISSUE THREAD

**Issue by ttr** [radx5Blue/ImmersiveSolarArrays#16]
Add wind power.

from code, this should not be too much to ask, as wind-speed is reported by ```getClimateManager():getWindPower()``` (and it's 0-1 float)
This is map-global, so need to be checked only once per all turbines, and IIRC, climateManaget is updated every 10-ingame minutes.

I've tried to do this as separate mod that would use ISA framework, but tapping into functions of what is on which grid was bit too complex.

Alternative, can you (in future) provide way of adding custom power generators (and perhaps consumers)?

**Comment by Poltergeistzx** [comment]
There's another windturbine mod under development
