### ISSUE TITLE
[feature] Provide charge rate information in "Power bank status"

### ISSUE THREAD

**Issue by ttr** [radx5Blue/ImmersiveSolarArrays#17]
Using power bank status, will tell you if change of battery is positive or negative but doesn't tell by how much - it's trial and error to know "can i run another fridge or only a lamp?"
IRL charge (and discharge) will be described by Amps difference, but in PZ this would give almost no information.

I think, using actualCharge, capacity and difference variables, time to full charge/discharge could be calculated and if so, that information can be "said".
Let's also say, that if this time is more than 24h it could say "enough to survive day", to not break immersion.

**Comment by ttr** [comment]
done this very hacky (and didn't actually make local repo to make this as PR)
ISAUI.lua
lines 137-160, replaced with:
```
		if noPZ > 1 then
			local text = "There are currently " .. noPZ .. " solar panels connected"
			player:Say(text)
		end
		
		if difference > 0 then
		    local dtime = ((capacity - actualCharge) / difference / 6)
			local text4 = "The battery bank has enough solar panels to power my connected devices"
			if dtime > 0 then
				lext4 = lext4 .. " It will take about " .. math.abs(math.floor(dtime)) .. " hours to fully charge"
			end
			player:Say(text4)
		end
		
		if difference == 0 then
			local text4 = "The battery bank has enough solar panels to power my connected devices but not to charge batteries"
			player:Say(text4)
		end
		
		if difference < 0 then
		    local dtime = ((actualCharge / difference) / 6)
			local text4 = ""
			if input > 0 then
				text4 = "I need more solar panels to power my devices.
			else
				text4 = "Panels do not generate electricity - need to check durin sunny day."
		    end
			text4 = text4 .. " Power will remain for about " .. math.abs(math.floor(dtime)) .. "hours."
			player:Say(text4)
		end
		
		if batterynumber == 0 then
			local text3 = "There are no batteries to charge up the battery bank"
			player:Say(text3)
		end
```

I do hope my logic is correct.

**Comment by radx5Blue** [comment]
I haven't tested this but if it works I am happy to add it in, it all looks correct to me. 

I don't have Zomboid installed and ready for modding at the moment, not until the end of Jan.

**Comment by ttr** [comment]
Take your time. This is code I do use on my local copy and seems to be working fine.

**Comment by radx5Blue** [comment]
I have added this to the mod.
