### ISSUE TITLE
[feature request] List Connected Devices

### ISSUE THREAD

**Issue by radx5Blue** [radx5Blue/ImmersiveSolarArrays#18]
An option like "List connected devices" to the powerbank like the generator has to check if the bank is powering all my stuff maybe also list there how much each device is using too

**Comment by Danixu** [comment]
Nice feature!. Maybe it can be together with this:

https://github.com/radx5Blue/ImmersiveSolarArrays/issues/22

- First tab for the general status
- Another tab for the connected devices list and if possible it consumption
- Maybe more...

Best regards

**Comment by ttr** [comment]
I think You already have this but only in debug mode (second tab and much more).
Perhaps an quick win would be to show 2nd tab in normal mode and only gatekeep using debug, detailed information about exact-power use/produce

**Comment by Poltergeistzx** [comment]
Added, might expand on it later.
