### ISSUE TITLE
[Question] Store data in server side

### ISSUE THREAD

**Issue by Danixu** [radx5Blue/ImmersiveSolarArrays#26]
Hello,

I have tried the Discord link but looks like it doesn't work, so I ask here (maybe another people know about it and can help).

I want to continue improving a bit this project because it looks very good and I think that can be even better
To make it a bit better in the MP part, I want to move all the module logic to the server side. This will allow to avoid that if you have 20 clients in the server, to have to calculate the solar status in all of them. Also will allow to a server that doesn't have activated the pause when no clients are connected, to still calculating the energy status and batteries degradation even when no one is connected.

My problem with this is that I have not found a way to save data in server side in a permanent way to allow the module to continue working in a normal way upon restarts. On client side I know that there is an object called modData which allows to store data premanently in the client, but on server that data is only stored while the server is running. Once is restarted, that data is lost.

My question is just if someone knows a way to store data in server side, because I want to store at least the PowerBanks position in the map. Also a way to locate objects in the map will be valid, because it must be done once at server start. This will allow to scan the surrounded objects to detect the consumers and the solar panels attached to that power bank.

I have asked in the official forum, but or no one cares, or there is no way to do it.

Best regards.

**Comment by Danixu** [comment]
Well,

Maybe my problem is already fixed... about three weeks searching for a way to do it and now just before writing the above I have seen this in the latest version changelog:
```
Fixed GlobalModData.save() not being called on the server.
```

I'll do some tests tomorrow and I'll close this if works.

Best regards.

**Comment by Danixu** [comment]
I had no luck, so I still searching for it.

**Comment by radx5Blue** [comment]
Hey Danixu

This is a quick example for saving data on the server

This needs to go in the client folder

`local onKeyPressed = function(key)
    local source = getPlayer(); if not source then return end

    if key == Keyboard.KEY_SPACE then
        local sourceId = source:getOnlineID();
		
		if ModData.exists("MyName") == false then
			ModData.create("MyName")
		end
		
		local MyName = {}
		table.insert(MyName, 1, "Hello")
		
		ModData.add("MyName", MyName)
		
		ModData.transmit("MyName")
		print("sending data")
        
    end

        
    end
	
	
function DataCheck()
	
	
	if ModData.request("MyName") ~= false then
	print(ModData.request("MyName"))
	end
	

end


Events.OnKeyPressed.Add(onKeyPressed);
Events.EveryTenMinutes.Add(DataCheck)`


and this needs to go in server folder

`function GotData(globalkey, globaltable)
	
	print("getting data")

	if globalkey ~= nil then
	ModData.add(globalkey, globaltable)
	
	print("Server Key: ", globalkey)
end
		
	--ModData.transmit("MyName")

end

Events.OnReceiveGlobalModData.Add(GotData)`


It's not 100% but it is the general idea I was working with.

**Comment by radx5Blue** [comment]
local onKeyPressed = function(key)
    local source = getPlayer(); if not source then return end

    if key == Keyboard.KEY_SPACE then
        local sourceId = source:getOnlineID();
		
		if ModData.exists("MyName") == false then
			ModData.create("MyName")
		end
		
		local MyName = {}
		table.insert(MyName, 1, "Hello")
		
		ModData.add("MyName", MyName)
		
		ModData.transmit("MyName")
		print("sending data")
        
    end

        
    end
	
	
function DataCheck()
	
	
	if ModData.request("MyName") ~= false then
	print(ModData.request("MyName"))
	end
	

end


Events.OnKeyPressed.Add(onKeyPressed);
Events.EveryTenMinutes.Add(DataCheck)

**Comment by radx5Blue** [comment]
server invite
https://discord.gg/PUjYKbAY

**Comment by radx5Blue** [comment]
I can't get the format right in the comments, if you are having trouble with the format let me know and I will upload the files

**Comment by Danixu** [comment]
Thanks!!, I'll give a try to see if I can make it work. If works I'll try to move the logic to the server side and if I can to add the connected devices list.

**Comment by Poltergeistzx** [comment]
Global object update does that
