### ISSUE TITLE
picking up battery bank do not clear panel connections

### ISSUE THREAD

**Issue by ttr** [radx5Blue/ImmersiveSolarArrays#40]
**Describe the bug**
When you pick up battery bank and move it to new location and place it down, all previous solar panels that where connected to battery bank are still connected

**To Reproduce**
1. have working ISA system
2. remove batteries from bank
3. pick up battery bank
4, place battery bank (in my situation it was 4 map cells away, nowhere near old location)

**Expected behavior**
when picking up battery bank all connections to solar panels should be cleared.

**Screenshots**
m/a

**Comment by ttr** [comment]
Also, when picking up solar panel it seems to de-registered it from power bank, but after placing it back the connect function is somehow broken - timed action is instant but it register to new power bank.

**Comment by Poltergeistzx** [comment]
Do you have any mods that affect the ISMoveablesAction perform?

**Comment by ttr** [comment]
will try to test this in isolated game play latter toda.
re-version, I'm using steam version (https://steamcommunity.com/sharedfiles/filedetails/?id=2623458493) so if it's not the recent one, is there other steam upload I shall use or github is the best to go?

**Comment by ttr** [comment]
OK, using GitHub version does fix those problems.
