### ISSUE TITLE
[feature request] To be possible to turn on / off battery banks

### ISSUE THREAD

**Issue by eaarsand** [radx5Blue/ImmersiveSolarArrays#6]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Right clicking a battey bank, allow the player to turn on / off the battery bank. Sometimes you are going to be a long time away from your base and don't need the batteries to be used or charged, so you can conserve them.

**Describe alternatives you've considered**
For now, i just remove the batteries from the banks.

**Additional context**
None.

**Comment by radx5Blue** [comment]
This is a good idea, I will take a look, shouldn't be too hard to implement.
