### ISSUE TITLE
[bug] [sprites] Loading Issues for 41.60 MP - Dedicated Server

### ISSUE THREAD

**Issue by DaNeo61** [radx5Blue/ImmersiveSolarArrays#7]
I Just want to Inform you, awesome mod !

> 
> LOG  : Lua         , 1639141812966> 30.553.287> Loading: steamapps/workshop/content/108600/2623458493/mods/ImmersiveSolarArrays/media/lua/server/items/ISADistList.lua
> LOG  : General     , 1639141812967> 30.553.287> -------------------------------------------------------------
> attempted index: items of non-table: null
> 
> LOG  : General     , 1639141812967> 30.553.287> -----------------------------------------
> STACK TRACE
> -----------------------------------------
> function: registerAsLoot -- file: ISADistList.lua line # 6
> function: ISADistList.lua -- file: ISADistList.lua line # 53
> 
> ERROR: General     , 1639141812967> 30.553.288> ExceptionLogger.logException> Exception thrown java.lang.RuntimeException: attempted index: items of non-table: null at KahluaThread.tableget line:1689.
> ERROR: General     , 1639141812967> 30.553.288> DebugLogStream.printException> Stack trace:
> java.lang.RuntimeException: attempted index: items of non-table: null
> 	at se.krka.kahlua.vm.KahluaThread.tableget(KahluaThread.java:1689)
> 	at se.krka.kahlua.vm.KahluaThread.luaMainloop(KahluaThread.java:492)
> 	at se.krka.kahlua.vm.KahluaThread.call(KahluaThread.java:163)
> 	at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1980)
> 	at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1782)
> 	at se.krka.kahlua.integration.LuaCaller.pcall(LuaCaller.java:76)
> 	at se.krka.kahlua.integration.LuaCaller.protectedCall(LuaCaller.java:117)
> 	at zombie.Lua.LuaManager.RunLuaInternal(LuaManager.java:549)
> 	at zombie.Lua.LuaManager.RunLua(LuaManager.java:495)
> 	at zombie.Lua.LuaManager.RunLua(LuaManager.java:481)
> 	at zombie.Lua.LuaManager.LoadDirBase(LuaManager.java:328)
> 	at zombie.Lua.LuaManager.LoadDirBase(LuaManager.java:255)
> 	at zombie.network.GameServer.doMinimumInit(GameServer.java:1368)
> 	at zombie.network.GameServer.main(GameServer.java:665)
> LOG  : General     , 1639141812967> 30.553.288> -----------------------------------------
> STACK TRACE
> -----------------------------------------
> function: registerAsLoot -- file: ISADistList.lua line # 6
> function: ISADistList.lua -- file: ISADistList.lua line # 53
> 
> Dez. 10, 2021 2:10:12 PM zombie.Lua.LuaManager RunLuaInternal
> SCHWERWIEGEND:  java.lang.RuntimeException
> Dez. 10, 2021 2:10:12 PM zombie.Lua.LuaManager RunLuaInternal
> SCHWERWIEGEND: java.lang.RuntimeException: 
> Dez. 10, 2021 2:10:12 PM zombie.Lua.LuaManager RunLuaInternal
> SCHWERWIEGEND: at registerAsLoot:6
> at ISADistList.lua:53

>LOG  : Lua         , 1639141812939> 30.553.259> Loading: steamapps/workshop/content/108600/2623458493/mods/ImmersiveSolarArrays/media/lua/server/ISAPowerBank/ISAPowerSystem.lua
> LOG  : General     , 1639141812941> 30.553.261> -------------------------------------------------------------
> attempted index: transferItem of non-table: null
> 
> LOG  : General     , 1639141812942> 30.553.263> -----------------------------------------
> STACK TRACE
> -----------------------------------------
> function: ISAPowerSystem.lua -- file: ISAPowerSystem.lua line # 152
> 
> ERROR: General     , 1639141812943> 30.553.263> ExceptionLogger.logException> Exception thrown java.lang.RuntimeException: attempted index: transferItem of non-table: null at KahluaThread.tableget line:1689.
> ERROR: General     , 1639141812943> 30.553.264> DebugLogStream.printException> Stack trace:
> java.lang.RuntimeException: attempted index: transferItem of non-table: null
> 	at se.krka.kahlua.vm.KahluaThread.tableget(KahluaThread.java:1689)
> 	at se.krka.kahlua.vm.KahluaThread.luaMainloop(KahluaThread.java:492)
> 	at se.krka.kahlua.vm.KahluaThread.call(KahluaThread.java:163)
> 	at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1980)
> 	at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1782)
> 	at se.krka.kahlua.integration.LuaCaller.pcall(LuaCaller.java:76)
> 	at se.krka.kahlua.integration.LuaCaller.protectedCall(LuaCaller.java:117)
> 	at zombie.Lua.LuaManager.RunLuaInternal(LuaManager.java:549)
> 	at zombie.Lua.LuaManager.RunLua(LuaManager.java:495)
> 	at zombie.Lua.LuaManager.RunLua(LuaManager.java:481)
> 	at zombie.Lua.LuaManager.LoadDirBase(LuaManager.java:328)
> 	at zombie.Lua.LuaManager.LoadDirBase(LuaManager.java:255)
> 	at zombie.network.GameServer.doMinimumInit(GameServer.java:1368)
> 	at zombie.network.GameServer.main(GameServer.java:665)
> LOG  : General     , 1639141812943> 30.553.264> -----------------------------------------
> STACK TRACE
> -----------------------------------------
> function: ISAPowerSystem.lua -- file: ISAPowerSystem.lua line # 152
> 
> Dez. 10, 2021 2:10:12 PM zombie.Lua.LuaManager RunLuaInternal
> SCHWERWIEGEND:  java.lang.RuntimeException
> Dez. 10, 2021 2:10:12 PM zombie.Lua.LuaManager RunLuaInternal
> SCHWERWIEGEND: java.lang.RuntimeException: 
> Dez. 10, 2021 2:10:12 PM zombie.Lua.LuaManager RunLuaInternal
> SCHWERWIEGEND: at ISAPowerSystem.lua:152

**Comment by DaNeo61** [comment]
weired formating on github ....

**Comment by radx5Blue** [comment]
Are you using the new update? I haven't tested it with that yet.
________________________________

**Comment by DaNeo61** [comment]
yeah its the new build 41.60, i just wanted to inform you what kind of error apears

**Comment by radx5Blue** [comment]
Thanks, I think the new build has broken something, I haven't had a chance to test.

Ill see what I can do over the next few days.
Thanks again
________________________________

**Comment by DaNeo61** [comment]
The mod is still loading and showed, i will send errors or problems when some appears

**Comment by radx5Blue** [comment]
Thanks, that will help
________________________________

**Comment by Salads** [comment]
@radx5Blue Hello, I like your mod! I think I found the issue... 

In `ISADistList.lua`, there are instances of the string "GarageMechanic", which no longer exist in the table they get indexed into. If you replace those strings with "GarageMechanics" (plural), it seems to work.

**Comment by radx5Blue** [comment]
Hey, I haven't had a chance to look at it all yet, but I will add that fix to my list, thank you.

Next week I'm going to start fixing it for the new update and MP.
________________________________

**Comment by pvm** [comment]
Hey! Any news on this? Craving to use this mod!

**Comment by radx5Blue** [comment]
Someone has created a patch, and it will load now, but there is some issues when playing on a multiplayer server, but you can download the latest of gihub.

**Comment by Fatmice** [comment]
This error remains
```
STACK TRACE
-----------------------------------------
function: ISAPowerSystem.lua -- file: ISAPowerSystem.lua line # 152

ERROR: General     , 1643268680725> 1,669,498,754> ExceptionLogger.logException> Exception thrown java.lang.RuntimeException: attempted index: transferItem of non-table: null at KahluaThread.tableget line:1689.
ERROR: General     , 1643268680725> 1,669,498,754> DebugLogStream.printException> Stack trace:
java.lang.RuntimeException: attempted index: transferItem of non-table: null
	at se.krka.kahlua.vm.KahluaThread.tableget(KahluaThread.java:1689)
	at se.krka.kahlua.vm.KahluaThread.luaMainloop(KahluaThread.java:492)
	at se.krka.kahlua.vm.KahluaThread.call(KahluaThread.java:163)
	at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1980)
	at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1782)
	at se.krka.kahlua.integration.LuaCaller.pcall(LuaCaller.java:76)
	at se.krka.kahlua.integration.LuaCaller.protectedCall(LuaCaller.java:117)
	at zombie.Lua.LuaManager.RunLuaInternal(LuaManager.java:550)
	at zombie.Lua.LuaManager.RunLua(LuaManager.java:496)
	at zombie.Lua.LuaManager.RunLua(LuaManager.java:482)
	at zombie.Lua.LuaManager.LoadDirBase(LuaManager.java:329)
	at zombie.Lua.LuaManager.LoadDirBase(LuaManager.java:256)
	at zombie.network.GameServer.doMinimumInit(GameServer.java:1364)
	at zombie.network.GameServer.main(GameServer.java:668)
LOG  : General     , 1643268680726> 1,669,498,754> -----------------------------------------
STACK TRACE
-----------------------------------------
function: ISAPowerSystem.lua -- file: ISAPowerSystem.lua line # 152

Jan 27, 2022 1:31:20 AM zombie.Lua.LuaManager RunLuaInternal
SEVERE:  java.lang.RuntimeException
Jan 27, 2022 1:31:20 AM zombie.Lua.LuaManager RunLuaInternal
SEVERE: java.lang.RuntimeException: 
Jan 27, 2022 1:31:20 AM zombie.Lua.LuaManager RunLuaInternal
SEVERE: at ISAPowerSystem.lua:152
```

**Comment by cosmic94** [comment]
yo first off, you rock for this thing, i had a ton of fun with it before the mp build 41 update. i have this ^^ same error, function ISInventoryTransferAction:transferItem(item), something wrong about how transferItem is being passed to the function?  i saw the issue for ISADist and was able to fix that, but this chunky 300~ line function is intimidating lol, and i definitely consider this a very essential mod, one of my favorites :/

`STACK TRACE
-----------------------------------------
function: ISAPowerSystem.lua -- file: ISAPowerSystem.lua line # 152

ERROR: General     , 1643947310681> 48,662,558> ExceptionLogger.logException> Exception thrown java.lang.RuntimeException: attempted index: transferItem of non-table: null at KahluaThread.tableget line:1689.
ERROR: General     , 1643947310681> 48,662,558> DebugLogStream.printException> Stack trace:
java.lang.RuntimeException: attempted index: transferItem of non-table: null
        at se.krka.kahlua.vm.KahluaThread.tableget(KahluaThread.java:1689)
        at se.krka.kahlua.vm.KahluaThread.luaMainloop(KahluaThread.java:492)
        at se.krka.kahlua.vm.KahluaThread.call(KahluaThread.java:163)
        at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1980)
        at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1782)
        at se.krka.kahlua.integration.LuaCaller.pcall(LuaCaller.java:76)
        at se.krka.kahlua.integration.LuaCaller.protectedCall(LuaCaller.java:117)
        at zombie.Lua.LuaManager.RunLuaInternal(LuaManager.java:550)
        at zombie.Lua.LuaManager.RunLua(LuaManager.java:496)
        at zombie.Lua.LuaManager.RunLua(LuaManager.java:482)
        at zombie.Lua.LuaManager.LoadDirBase(LuaManager.java:329)
        at zombie.Lua.LuaManager.LoadDirBase(LuaManager.java:256)
        at zombie.network.GameServer.doMinimumInit(GameServer.java:1364)
        at zombie.network.GameServer.main(GameServer.java:668)
LOG  : General     , 1643947310689> 48,662,566> -----------------------------------------
STACK TRACE`

**Comment by ttr** [comment]
the  ISAPowerSystem.lua line # 152 - looks like is caused, that ISInventoryTransferAction is client side function, but it's used in server side LUA - this will work in SP as server and client functions are loaded together.

**Comment by Fatmice** [comment]
> the ISAPowerSystem.lua line # 152 - looks like is caused, that ISInventoryTransferAction is client side function, but it's used in server side LUA - this will work in SP as server and client functions are loaded together.

So the fix is to then move that block to a file in client folder in the mod?

**Comment by radx5Blue** [comment]
So this is 'fixed', I removed that part from the ISAPowerSystem for now, the battery bank sprite won't update right away anymore it will update next time it does a check, but at least there won't be errors, I will come back to the sprite later and try a different solution to fix it, that doesn't use client side functions.
